<?php
header("Cache-Control: no-store, no-cache, must-revalidate, max-age=0");
header("Cache-Control: post-check=0, pre-check=0", false);
header("Pragma: no-cache");

include 'incl/colors_lib.php';
include 'incl/signature_lib.php';


function make_signature($player_id){

	$labels = new signature($player_id);
	$sign_save_dir = "autogenerated/".$player_id.".png";

	$label_font = "Arvo-Regular.ttf";

	$bg_img = imagecreatefrompng('img/background.png');

	list($src_w,$src_h,$src_type) = getimagesize('img/background.png');

	$signature = imagecreatetruecolor($src_w, $src_h);
	imagesavealpha($signature, true);

	imagecopy($signature, $bg_img, 0, 0, 0, 0, $src_w, $src_h);

	$ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $labels->getValue("clan_icon")); 
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_BINARYTRANSFER, 1);
    $data = curl_exec($ch);
    curl_close($ch);

    $clan_icon = imagecreatefromstring($data);
	imagecopy($signature, $clan_icon, 10, 10, 0, 0, imagesx($clan_icon), imagesy($clan_icon));

	$clan_rank = imagecreatefrompng('img/epaulettes/'.$labels->getValue("clan_rank").'.png');
	imagecopy($signature, $clan_rank, $src_w-35, $src_h-38, 0, 0, imagesx($clan_rank), imagesy($clan_rank));

	$RGB = hex2RGB("FFFFFF");
	$color_label = imagecolorallocatealpha($signature, $RGB['red'], $RGB['green'], $RGB['blue'], 63);

	$RGB = hex2RGB(str_replace("#", "", $labels->getValue("clan_color")));
	$color_clan = imagecolorallocate($signature, $RGB['red'], $RGB['green'], $RGB['blue']);

	$RGB = hex2RGB(winrate_color::getter($labels->getValue("winrate")));
	$color_WR = imagecolorallocate($signature, $RGB['red'], $RGB['green'], $RGB['blue']);

	// $RGB = hex2RGB(winrate_color::getter($labels->getValue("r_winrate")));
	// $color_rWR = imagecolorallocate($signature, $RGB['red'], $RGB['green'], $RGB['blue']);

	$RGB = hex2RGB(wn8_color::getter($labels->getValue("WN8")));
	$color_WN8 = imagecolorallocate($signature, $RGB['red'], $RGB['green'], $RGB['blue']);

	// $RGB = hex2RGB(wn8_color::getter($labels->getValue("r_WN8")));
	// $color_rWN8 = imagecolorallocate($signature, $RGB['red'], $RGB['green'], $RGB['blue']);

	imagettftext($signature, 10, 0, 135, 20, $color_label, $label_font, $labels->getValue("battles"));
	imagettftext($signature, 10, 0, 135, 45, $color_label, $label_font, $labels->getValue("avg_exp"));
	imagettftext($signature, 10, 0, 135, 75, $color_label, $label_font, $labels->getValue("avg_dmg"));

	imagettftext($signature, 10, 0, 240, 20, $color_label, $label_font, $labels->getValue("avg_frags"));
	imagettftext($signature, 10, 0, 240, 45, $color_label, $label_font, $labels->getValue("avg_tier"));
	imagettftext($signature, 10, 0, 240, 75, $color_label, $label_font, $labels->getValue("hitratio"));

	imagettftext($signature, 13, 0, 5, 103, $color_clan, $label_font, "[".$labels->getValue("clan_name")."]");

	$bbox = imagettfbbox(13, 0, $label_font, $labels->getValue("nickname"));
	$offsetX = $src_w/2 - ($bbox[2]-$bbox[0])/2;
	imagettftext($signature, 13, 0, $offsetX, 103, $color_label, $label_font, $labels->getValue("nickname"));

	// imagettftext($signature, 8, 0, 305, 40, $color_rWR, $label_font, $labels->getValue("r_winrate"));
	imagettftext($signature, 8, 0, 305, 80, $color_WR, $label_font, $labels->getValue("winrate"));

	// imagettftext($signature, 8, 0, 365, 40, $color_rWN8, $label_font, $labels->getValue("r_WN8"));
	imagettftext($signature, 8, 0, 365, 80, $color_WN8, $label_font, $labels->getValue("WN8"));


	$progres_start = $src_w-23;

	$lt_right = imagecreatefrompng('img/progressbars/bar_lt_right.png');
	imagecopy($signature, $lt_right, $progres_start, 2, 0, 0, imagesx($lt_right), imagesy($lt_right));

	$mt_right = imagecreatefrompng('img/progressbars/bar_mt_right.png');
	imagecopy($signature, $mt_right, $progres_start, 18, 0, 0, imagesx($mt_right), imagesy($mt_right));

	$ht_right = imagecreatefrompng('img/progressbars/bar_ht_right.png');
	imagecopy($signature, $ht_right, $progres_start, 35, 0, 0, imagesx($ht_right), imagesy($ht_right));

	$td_right = imagecreatefrompng('img/progressbars/bar_td_right.png');
	imagecopy($signature, $td_right, $progres_start, 51, 0, 0, imagesx($td_right), imagesy($td_right));

	$spg_right = imagecreatefrompng('img/progressbars/bar_spg_right.png');
	imagecopy($signature, $spg_right, $progres_start, 67, 0, 0, imagesx($spg_right), imagesy($spg_right));


	$max_bar_val = max($labels->getValue("btl_lt"),$labels->getValue("btl_mt"),$labels->getValue("btl_ht"),$labels->getValue("btl_td"),$labels->getValue("btl_spg"));
	$bar_size = 35;
	$lt_progress = calculateProgress($max_bar_val, $labels->getValue("btl_lt"), $bar_size);
	$mt_progress = calculateProgress($max_bar_val, $labels->getValue("btl_mt"), $bar_size);
	$ht_progress = calculateProgress($max_bar_val, $labels->getValue("btl_ht"), $bar_size);
	$td_progress = calculateProgress($max_bar_val, $labels->getValue("btl_td"), $bar_size);
	$spg_progress = calculateProgress($max_bar_val, $labels->getValue("btl_spg"), $bar_size);

	
	$lt_middle = imagecreatefrompng('img/progressbars/bar_lt_middle.png');

	$progr_x = 0;
	while ($progr_x <= $lt_progress) {
		imagecopy($signature, $lt_middle, $progres_start - $progr_x, 2, 0, 0, imagesx($lt_middle), imagesy($lt_middle));
		$progr_x += imagesx($lt_middle);
	}

	$mt_middle = imagecreatefrompng('img/progressbars/bar_mt_middle.png');

	$progr_x = 0;
	while ($progr_x <= $mt_progress) {
		imagecopy($signature, $mt_middle, $progres_start - $progr_x, 18, 0, 0, imagesx($mt_middle), imagesy($mt_middle));
		$progr_x += imagesx($mt_middle);
	}

	$ht_middle = imagecreatefrompng('img/progressbars/bar_ht_middle.png');

	$progr_x = 0;
	while ($progr_x <= $ht_progress) {
		imagecopy($signature, $ht_middle, $progres_start - $progr_x, 35, 0, 0, imagesx($ht_middle), imagesy($ht_middle));
		$progr_x += imagesx($ht_middle);
	}

	$td_middle = imagecreatefrompng('img/progressbars/bar_td_middle.png');

	$progr_x = 0;
	while ($progr_x <= $td_progress) {
		imagecopy($signature, $td_middle, $progres_start - $progr_x, 51, 0, 0, imagesx($td_middle), imagesy($td_middle));
		$progr_x += imagesx($td_middle);
	}

	$spg_middle = imagecreatefrompng('img/progressbars/bar_spg_middle.png');

	$progr_x = 0;
	while ($progr_x <= $spg_progress) {
		imagecopy($signature, $spg_middle, $progres_start - $progr_x, 67, 0, 0, imagesx($spg_middle), imagesy($spg_middle));
		$progr_x += imagesx($spg_middle);
	}
	

	$lt_left = imagecreatefrompng('img/progressbars/bar_lt_left.png');
	imagecopy($signature, $lt_left, $progres_start - imagesx($lt_left) - $lt_progress, 2, 0, 0, imagesx($lt_left), imagesy($lt_left));

	$mt_left = imagecreatefrompng('img/progressbars/bar_mt_left.png');
	imagecopy($signature, $mt_left, $progres_start - imagesx($lt_left) - $mt_progress, 18, 0, 0, imagesx($mt_left), imagesy($mt_left));

	$ht_left = imagecreatefrompng('img/progressbars/bar_ht_left.png');
	imagecopy($signature, $ht_left, $progres_start - imagesx($lt_left) - $ht_progress, 35, 0, 0, imagesx($ht_left), imagesy($ht_left));

	$td_left = imagecreatefrompng('img/progressbars/bar_td_left.png');
	imagecopy($signature, $td_left, $progres_start - imagesx($lt_left) - $td_progress, 51, 0, 0, imagesx($td_left), imagesy($td_left));

	$spg_left = imagecreatefrompng('img/progressbars/bar_spg_left.png');
	imagecopy($signature, $spg_left, $progres_start - imagesx($lt_left) - $spg_progress, 67, 0, 0, imagesx($spg_left), imagesy($spg_left));


	imagettftext($signature, 8, 0, 410, 14, $color_label, $label_font, $labels->getValue("btl_lt"));
	imagettftext($signature, 8, 0, 410, 30, $color_label, $label_font, $labels->getValue("btl_mt"));
	imagettftext($signature, 8, 0, 410, 47, $color_label, $label_font, $labels->getValue("btl_ht"));
	imagettftext($signature, 8, 0, 410, 63, $color_label, $label_font, $labels->getValue("btl_td"));
	imagettftext($signature, 8, 0, 410, 79, $color_label, $label_font, $labels->getValue("btl_spg"));

	// session_start(); 
	// header("Cache-Control: private, max-age=10800, pre-check=10800");
	// header("Pragma: private");
	// header("Expires: " . date(DATE_RFC822,strtotime(" 7 days")));
	header("Content-type: image/png");
	imagepng($signature);
	imagepng($signature, $sign_save_dir);


	imagedestroy($lt_right);
	imagedestroy($mt_right);
	imagedestroy($ht_right);
	imagedestroy($td_right);
	imagedestroy($spg_right);

	imagedestroy($lt_middle);
	imagedestroy($mt_middle);
	imagedestroy($ht_middle);
	imagedestroy($td_middle);
	imagedestroy($spg_middle);

	imagedestroy($lt_left);
	imagedestroy($mt_left);
	imagedestroy($ht_left);
	imagedestroy($td_left);
	imagedestroy($spg_left);

	imagedestroy($clan_icon);
	imagedestroy($clan_rank);
	imagedestroy($bg_img);
	imagedestroy($signature);
}

$player_id = $_GET['id'];

if (isset($player_id) && is_numeric($player_id)) {
	make_signature($player_id);
}else{
	header("HTTP/1.0 404 Not Found");
	die('Page not found.');
}

?>